[build-system] 
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
 
[project]
name = "tw-etl" 
version = "0.1"
requires-python = ">=3.9"
dependencies=[
    "aiohttp",
    "pyyaml"
]

[project.urls] 
"Homepage" = "" 

